name: Docker Image CI

on:
  push:
    branches: [ "main" ] # or your main development branch
  pull_request:
    branches: [ "main" ] # optional: trigger on pull requests

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Use a fresh Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Match your project's Go version
        cache: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Build context is the root of the repository
        push: true # Push the image to the registry
        tags: your-dockerhub-username/protobuf-serdeser:latest # Replace with your Docker Hub username and repo name
        platforms: linux/amd64 # Specify platform if needed

    - name: Verify pushed image (Optional)
      run: echo "Docker image your-dockerhub-username/protobuf-serdeser:latest pushed successfully!" # Replace with your Docker Hub username and repo name
